### ISSUE TITLE
replace "downsampleFactor" argument by "image_mpp" 

### ISSUE THREAD

**Issue by YiyuHong** [HMS-IDAC/UNetCoreograph#16]
Hi, How about replace `--downsampleFactor` argument by `--image_mpp` like in mesmer.
For example, it says the UNetCoreograph is trained with images with mpp=0.2, if an image of a user is mpp=0.5, then the user just need to input `--image_mpp 0.5`, and it is automatically calculate the variable `downsampleFactor` or `dsFactor`

Thanks

**Comment by clarenceyapp** [comment]
Yes, we are working on rolling out alot of improved features including this in the next iteration of MCMICRO
